image: takkatakka/lftp

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mkdir ~/.ssh
  - echo "$SSH_KEY" > ~/.ssh/id_rsa
  - ssh-keyscan -H '$HOST'
  - chmod -R 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_moe:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd kmserver; mirror -Rnev --parallel=10 --exclude .git/ --exclude app/ --exclude config.yml --exclude database.json --exclude karaokemugen-app/ --exclude logs/ --exclude node_modules/ --exclude .next/ "
    - ssh -l $USERNAME $HOST 'cd kmserver ; yarn install ; yarn installAll ; yarn buildAll'
    - ssh -l $USERNAME $HOST 'sudo systemctl restart karaokemugen-server'
  environment:
    name: production-moe
    url: https://kara.moe
  only:
  - master

deploy_world:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd kmserver-world; mirror -Rnev --parallel=10 --exclude .git/ --exclude app/ --exclude config.yml --exclude database.json --exclude logs/ --exclude node_modules/ --exclude .next/ "
    - ssh -l $USERNAME $HOST 'cd kmserver-world ; yarn install ; yarn installAll ; yarn buildAll'
    - ssh -l $USERNAME $HOST 'sudo systemctl restart karaokemugen-server-world'
  environment:
    name: production-world
    url: https://world.karaokes.moe
  only:
  - master

deploy_dev:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd kmserver-dev; mirror -Rnev --parallel=10 --exclude .git/ --exclude app/ --exclude config.yml --exclude database.json --exclude karaokemugen-app/ --exclude logs/ --exclude node_modules/ --exclude .next/ "
    - ssh -l $USERNAME $HOST 'cd kmserver-dev ; yarn install ; yarn installAll ; yarn buildAll'
    - ssh -l $USERNAME $HOST 'sudo systemctl restart karaokemugen-server-dev'
  environment:
    name: dev
    url: https://dev.kara.moe
  only:
  - dev