image: takkatakka/lftp

stages:
  - deploy

before_script:
  - mkdir ~/.ssh
  - echo "$SSH_KEY" > ~/.ssh/id_rsa
  - ssh-keyscan -H '$HOST'
  - chmod -R 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_prod:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd kmserver; mirror -Rnev --parallel=10 --exclude .git --exclude app/ --exclude config.yml --exclude .pid --exclude database.json --exclude karaokemugen-app/ --exclude logs/ --exclude node_modules/ --exclude .next/ "
    - ssh -l $USERNAME $HOST 'cd kmserver ; yarn install ; yarn build ; cd kmexplorer ; yarn install ; rm -Rf .next ; npx next build --api=https://localhost:1350'
    - ssh -l $USERNAME $HOST 'sudo systemctl stop karaokemugen-server ; cd kmserver ; rm *.pid ; sudo systemctl start karaokemugen-server'
  environment:
    name: production
    url: https://kara.moe
  only:
  - master


deploy_dev:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd kmserver-dev; mirror -Rnev --parallel=10 --exclude .git --exclude app/ --exclude config.yml --exclude .pid --exclude database.json --exclude karaokemugen-app/ --exclude logs/ --exclude node_modules/ --exclude .next/ "
    - ssh -l $USERNAME $HOST 'cd kmserver-dev ; yarn install ; yarn build ; cd kmexplorer ; yarn install ; rm -Rf .next ; npx next build --api=https://localhost:1450'
    - ssh -l $USERNAME $HOST 'sudo systemctl stop karaokemugen-server-dev ; cd kmserver-dev ;  rm *.pid ; sudo systemctl start karaokemugen-server-dev'
  environment:
    name: dev
    url: https://dev.kara.moe
  only:
  - dev
